name: Sync Forks (Hopefully)

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:

jobs:
  sync-forks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git Config
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'meefs-bot@rackhelp.com'

      - name: Sync Forked Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          USERNAME="meefs"
          PAGE=1
          PER_PAGE=30
          while : ; do
            REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/user/repos?type=forks&per_page=$PER_PAGE&page=$PAGE" \
              | jq -r '.[] | "\(.full_name) \(.parent.clone_url) \(.default_branch)"')
            if [ -z "$REPOS" ]; then
              break
            fi
            echo "$REPOS" | while read REPO CLONE_URL DEFAULT_BRANCH; do
              if [ ! -z "$REPO" ]; then
                echo "Syncing $REPO"
                git clone "https://x-access-token:$GITHUB_TOKEN@${CLONE_URL#https://}" repo
                cd repo
                git remote add upstream "${CLONE_URL/https:\/\/$USERNAME/https:\/\/}"
                git fetch upstream
                git checkout $DEFAULT_BRANCH
                git merge upstream/$DEFAULT_BRANCH --allow-unrelated-histories -m "Merged by GitHub Actions"
                git push origin $DEFAULT_BRANCH
                cd ..
                rm -rf repo
              fi
            done
            ((PAGE=PAGE+1))
          done
