name: Sync All Forks - Matrix Edition

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-output.outputs.matrix }}
    steps:
      - name: Fetch repositories and prepare matrix
        id: set-output
        run: |
          REPOS=$(curl -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/users/meefs/repos?type=forks")
          MATRIX=$(echo "$REPOS" | jq '.[] | .clone_url' | jq -s .)
          echo "::set-output name=matrix::$MATRIX"

  sync:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Sync repository
        run: |
          REPO_CLONE_URL="${{ matrix.repo }}"
          REPO_NAME=$(basename "$REPO_CLONE_URL" .git)
          
          git clone "$REPO_CLONE_URL" "$REPO_NAME"
          cd "$REPO_NAME"
          # Assuming 'main' as the default branch; adjust as needed
          git fetch origin main:main
          git merge origin/main
          git push origin main
          cd ..
          rm -rf "$REPO_NAME"
