name: Sync All Forks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-output.outputs.matrix }}
    steps:
      - name: Fetch repositories
        id: fetch-repos
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/users/meefs/repos?type=forks" > repos.json
          cat repos.json

      - name: Generate base64 list
        id: generate-list
        run: |
          jq -r '.[] | @base64' repos.json > repos_base64.txt
          cat repos_base64.txt

      - name: Set matrix output
        id: set-output
        run: |
          REPO_LIST=$(cat repos_base64.txt)
          MATRIX=$(cat repoos_base64.txt | while read -r line; do echo $line | base64 --decode; done | jq -s .)
          echo "::set-output name=matrix::$MATRIX"

  sync:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Decode repository information
        id: repo
        run: |
          REPO_INFO=$(echo "${{ matrix.repo }}" | base64 -d)
          REPO_FULL_NAME=$(echo $REPO_INFO | jq -r '.full_name')
          REPO_CLONE_URL=$(echo $REPO_INFO | jq -r '.clone_url')
          
          echo "Full name: $REPO_FULL_NAME"
          echo "Clone URL: $REPO_CLONE_URL"
      
      - name: Sync repository
        run: |
          git clone "$REPO_CLONE_URL" "$REPO_FULL_NAME"
          cd "$REPO_FULL_NAME"
          
          # Assuming 'main' as the default branch; adjust as needed
          git fetch origin main:main
          git merge origin/main
          git push origin main
          
          cd ..
          rm -rf "$REPO_FULL_NAME"
