name: Sync All Forks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate list of forked repositories
        id: set-matrix
        run: |
          REPOS=$(curl -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/users/meefs/repos?type=forks")
          REPO_LIST=$(echo "$REPOS" | jq -r '.[] | @base64')
          echo "::set-output name=matrix::$(echo "$REPO_LIST" | jq -sc .)"

  sync:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Decode repository information
        id: repo
        run: echo "${{ matrix.repo }}" | base64 -d
        shell: bash
      - name: Sync repository
        run: |
          REPO_INFO=${{ steps.repo.outputs.result }}
          REPO_FULL_NAME=$(echo $REPO_INFO | jq -r '.full_name')
          REPO_CLONE_URL=$(echo $REPO_INFO | jq -r '.clone_url')
          
          git clone "$REPO_CLONE_URL" "$REPO_FULL_NAME"
          cd "$REPO_FULL_NAME"
          git fetch origin main:main
          git merge origin/main
          git push origin main
          cd ..
          rm -rf "$REPO_FULL_NAME"
