name: Sync All Forks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  sync-forks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Sync all forks
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Using GitHub's built-in token for authentication
        run: |
          #!/bin/bash
          set -e

          # Fetch list of forked repositories for the user 'meefs'
          REPOS=$(curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/meefs/repos?type=forks")

          # Loop through each repository and sync
          echo "$REPOS" | jq -r '.[] | .full_name + " " + .clone_url' | while read -r REPO_FULL_NAME REPO_CLONE_URL; do
            # Extract repository name
            REPO_NAME=$(basename "$REPO_CLONE_URL" .git)
            
            # Clone the forked repository
            git clone "$REPO_CLONE_URL" "$REPO_NAME"
            cd "$REPO_NAME"
            
            # Assuming 'main' as the default branch; adjust as needed
            # Fetch updates from the original repository
            git fetch origin main:main
            
            # Optionally, merge changes from 'main' and push
            git merge origin/main
            git push origin main
            
            # Cleanup: Move out and remove the repo directory
            cd ..
            rm -rf "$REPO_NAME"
          done
