name: Update README with Forked Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Update README.md with forked repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          #!/bin/bash
          set -e

          # Check if jq is installed
          if ! command -v jq &> /dev/null; then
              echo "jq could not be found. Please ensure jq is installed in the runner environment."
              exit 1
          fi

          # Function to fetch repositories with pagination and error handling
          fetch_repos() {
            local page=1
            local all_repos="[]"
            
            while true; do
              echo "Fetching page $page of repositories..."
              local response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/users/meefs/repos?type=forks&per_page=100&page=$page")
              
              # Debug: Print the raw response
              echo "Raw API response for page $page:"
              echo "$response"
              
              # Check if the response is valid JSON
              if ! echo "$response" | jq empty 2>/dev/null; then
                echo "Error: Invalid JSON response from GitHub API on page $page"
                echo "Response: $response"
                return 1
              fi
              
              # Check if the response is empty or if we've reached the end
              if [ "$(echo "$response" | jq '. | length')" -eq 0 ]; then
                break
              fi
              
              # Combine the new results with the existing ones
              all_repos=$(echo "$all_repos" "$response" | jq -s 'add')
              
              ((page++))
            done
            
            echo "$all_repos"
          }

          # Fetch all forked repositories
          echo "Starting to fetch all forked repositories..."
          REPOS=$(fetch_repos)

          # Check if fetch_repos was successful
          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch repositories"
            exit 1
          fi

          # Debug: Print the final REPOS variable
          echo "Final REPOS variable:"
          echo "$REPOS" | jq '.'

          # Count total repositories
          REPO_COUNT=$(echo "$REPOS" | jq '. | length')
          echo "Total repositories fetched: $REPO_COUNT"

          # Generate repository content
          REPOS_CONTENT="## Forked Repositories\n\n"
          REPOS_CONTENT+="Last updated: $(date '+%Y-%m-%d %H:%M:%S')\n\n"
          REPOS_CONTENT+="Total repositories: $REPO_COUNT\n\n"

          # Process and sort repositories
          echo "$REPOS" | jq -r '.[] | [.language // "Unknown", .full_name, .html_url, .description // "No description"] | @tsv' | \
          sort -k1,1 | \
          while IFS=$'\t' read -r LANG NAME URL DESC; do
            if [ "$PREV_LANG" != "$LANG" ]; then
              REPOS_CONTENT+="### $LANG\n"
              PREV_LANG=$LANG
            fi
            REPOS_CONTENT+="- [$NAME]($URL): $DESC\n"
          done

          # Update README.md
          START_MARKER="<!-- START_SECTION:forked_repos -->"
          END_MARKER="<!-- END_SECTION:forked_repos -->"

          if grep -q "$START_MARKER" README.md && grep -q "$END_MARKER" README.md; then
            sed -i "/$START_MARKER/,/$END_MARKER/c\\$START_MARKER\\n$REPOS_CONTENT\\n$END_MARKER" README.md
          else
            echo -e "\n$START_MARKER\n$REPOS_CONTENT\n$END_MARKER" >> README.md
          fi

          # Git configuration and commit changes
          git config user.name "GitHub Actions"
          git config user.email "meefs-bot@rackhelp.com"

          if [[ -n $(git status -s) ]]; then
            git add README.md
            git commit -m "Update README.md with forked repositories"
            git push
          else
            echo "No changes to commit."
          fi