name: Update REPOS.md

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  update-repos-list:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Update REPOS.md with forked repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Using the specified token for authentication
        run: |
          #!/bin/bash
          set -e

          # Check if jq is installed
          if ! command -v jq &> /dev/null; then
              echo "jq could not be found. Please ensure jq is installed in the runner environment."
              exit 1
          fi

          # Fetch list of forked repositories for the user 'meefs'
          REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/meefs/repos?type=forks&per_page=200&page=1")

          # Initialize a temporary file to store intermediate results
          TEMP_FILE=$(mktemp)

          # Process each repository
          echo "$REPOS" | jq -c '.[]' | while read -r REPO; do
            REPO_FULL_NAME=$(echo "$REPO" | jq -r '.full_name')
            REPO_LANGUAGE=$(echo "$REPO" | jq -r '.language // "Unknown"')
            REPO_URL=$(echo "$REPO" | jq -r '.html_url')
            REPO_DESCRIPTION=$(echo "$REPO" | jq -r '.description // "No description"')

            # Append repository info to temporary file
            echo "$REPO_LANGUAGE|$REPO_FULL_NAME|$REPO_URL|$REPO_DESCRIPTION" >> "$TEMP_FILE"
          done

          echo "" > REPOS.md ## Clearing out any contents from previous REPOS.md

          # Sort and group by language
          sort "$TEMP_FILE" | while IFS="|" read -r LANG NAME URL DESC; do
            # Check if the current language section has changed and if so, start a new section
            if [ "$PREV_LANG" != "$LANG" ]; then
              if [ -n "$PREV_LANG" ]; then
                # Add a newline between language sections
                echo "" >> REPOS.md
              fi
              echo "## $LANG" >> REPOS.md
              PREV_LANG=$LANG
            fi

            # Append repository info under the current language section
            echo "- [$NAME]($URL): $DESC" >> REPOS.md
          done

          # Remove temporary file
          rm "$TEMP_FILE"

          # Git configuration
          git config --global user.name "GitHub Actions"
          git config --global user.email "meefs-bot@rackhelp.com"
          git config --global credential.helper store
          echo "https://x-access-token:$GITHUB_TOKEN@github.com" > ~/.git-credentials

          # Commit and push if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add REPOS.md
            git commit -m "Update REPOS.md with forked repositories"
            git push
          else
            echo "No changes to commit."
          fi
